---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: ruby
- name: rubygems
- name: libyaml
- name: bosh-src

outputs:
- name: bosh-src

run:
  path: bosh-src/ci/tasks/bump-ruby.sh

params:
  PRIVATE_YML:
  RUBY_VERSION:
  RUBYGEMS_VERSION:
  LIBYAML_VERSION:
