---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: postgres-src

outputs:
- name: bosh-src

run:
  path: bosh-src/ci/tasks/bump-postgres-packages.sh

params:
  PRIVATE_YML:
  MAJOR_VERSION:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: cf-bosh-eng@pivotal.io

