---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bosh-ci
- name: bosh
- name: postgres-src

outputs:
- name: bosh

run:
  path: bosh-ci/ci/tasks/bump-postgres-packages.sh

params:
  PRIVATE_YML:
  MAJOR_VERSION:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: cf-bosh-eng@pivotal.io

