---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bosh-ci
- name: bosh
- name: nats-server-github-release

outputs:
- name: bosh

run:
  path: bosh-ci/ci/tasks/bump-nats-server.sh

params:
  PRIVATE_YML:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: cf-bosh-eng@pivotal.io
