---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: bosh-ci

run:
  path: bosh-ci/ci/tasks/cleanup-leftovers.sh

params:
  GCP_JSON_KEY:
  LEFTOVERS_VERSION: latest
  LEFTOVERS_PREFIX:
