---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bosh-ci
- name: release
- name: stemcell

outputs:
- name: compiled-release

run:
  path: bosh-ci/ci/tasks/export-release.sh
