---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
  - name: bosh-ci
  - name: bosh
  - name: bosh-cli
  - name: version
  - name: release-tarball

outputs:
  - name: bosh
  - name: release-metadata

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-ci/ci/tasks/finalize-bosh-release.sh
