---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/aws-cpi-release

inputs:
- name: bosh-ci
- name: bosh-src
- name: bosh-cli

outputs:
- name: release

run:
  path: bosh-ci/ci/tasks/make-candidate.sh
