---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: bosh-ci
  - name: bosh-ci-dockerfiles
  - name: bosh-deployment
  - name: bosh-cli

run:
  path: bosh-ci/ci/tasks/prepare-container-docker-cpi-build-context.sh

outputs:
  - name: docker-build-context

