---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
  - name: bosh-src
  - name: bosh-cli
  - name: version

outputs:
  - name: bosh-src
  - name: release-tarball

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-src/ci/tasks/prepare-release.sh
