---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi

inputs:
  - name: bosh-ci
  - name: bosh-src
  - name: stemcell
  - name: bosh-release
  - name: cf-deployment

run:
  path: bosh-ci/ci/tasks/test-brats-performance.sh

