---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-postgres-15
    tag: main

inputs:
- name: bosh-ci
- name: bosh
- name: bosh-cli
- name: bosh-agent
- name: config-server

run:
  path: bosh-ci/ci/tasks/test-integration.sh

params:
  DB:                         postgresql
  DB_VERSION:                 15
  LOG_LEVEL:                  ERROR
  SPEC_PATH:                  ~
  SHA2_MODE:                  ~
  DEFAULT_UPDATE_VM_STRATEGY: "delete-create"
  NUM_PROCESSES:
  GOOS:                       linux
