---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/warden-cpi

inputs:
- name: bosh-ci
- name: stemcell
- name: bosh-release
- name: bosh-disaster-recovery-acceptance-tests
  path: gopath/src/github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests
- name: bbr-cli-binary
- name: bosh-deployment
  optional: true

run:
  path: bosh-ci/ci/tasks/test-bdrats.sh
