---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: stemcell

params:
  RUBY_VERSION:

run:
  path: bosh-src/ci/tasks/test-ruby.sh
