---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi

inputs:
  - name: bosh-ci
  - name: bosh
  - name: stemcell
  - name: bosh-release
  - name: cf-deployment

params:
  FOCUS_SPEC:
  START_INNER_BOSH_TIMEOUT: "" # default is 25m

run:
  path: bosh-ci/ci/tasks/test-brats-performance.sh

