---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
  - name: bosh-ci
  - name: bosh

run:
  path: bosh-ci/ci/tasks/test-rake-task.sh

params:
  COVERAGE:     true
  DB:           sqlite
  RAKE_TASK:
