---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration
    tag: main

inputs:
  - name: bosh-src
  - name: director-state
  - name: terraform

params:
  STEMCELL_NAME:

outputs:
  - name: bats-config

run:
  path: bosh-src/ci/bats/iaas/gcp/prepare-bats-config.sh
